--
-- _cmake.lua
-- Define the CMake action(s).
-- Copyright (c) 2015 Miodrag Milanovic
--

function premake.cmake.workspace(sln)
	if (sln.location ~= _WORKING_DIR) then
		local name = string.format("%s/CMakeLists.txt", _WORKING_DIR)
		local f, err = io.open(name, "wb")
		if (not f) then
			error(err, 0)
		end
		f:write([[
			# CMakeLists autogenerated by GENie
			# https://github.com/bkaradzic/GENie
			project(GENie)
			cmake_minimum_required(VERSION ]] .. premake.cmake.cmake_minimum_version .. [[)

			#########################################################################

			# Set a default build type if none was specified
			# Source: https://blog.kitware.com/cmake-and-the-default-build-type/
			set(default_build_type "Release")
			if(EXISTS "${CMAKE_SOURCE_DIR}/.git")
			  set(default_build_type "Debug")
			endif()
			if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
			  message(STATUS "Setting build type to '${default_build_type}' as none was specified.")
			  set(CMAKE_BUILD_TYPE "${default_build_type}" CACHE STRING "Choose the type of build." FORCE)
			  # Set the possible values of build type for cmake-gui
			  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
			endif()

			#########################################################################
		]])
		if os.is("windows") then
			-- Add support for CMP0091, see https://cmake.org/cmake/help/latest/policy/CMP0091.html
			f:write('cmake_policy(SET CMP0091 NEW)\n')
		end
		f:write('add_subdirectory('.. path.getrelative(_WORKING_DIR, sln.location) ..')\n')
		f:close()
	end
	_p('# CMakeLists autogenerated by GENie')
	_p('# https://github.com/bkaradzic/GENie')
	_p('cmake_minimum_required(VERSION %s)', premake.cmake.cmake_minimum_version)
	if os.is("windows") then
		-- Add support for CMP0091, see https://cmake.org/cmake/help/latest/policy/CMP0091.html
		_p('cmake_policy(SET CMP0091 NEW)')
	end
	_p('project(%s)', sln.name)
	_p('set(CMAKE_SUPPRESS_REGENERATION true)')
	_p('# Strip default /EHsc — each project manages exception handling explicitly')
	_p('if(MSVC)')
	_p(1, 'string(REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")')
	_p('endif()')
	_p('set_property(GLOBAL PROPERTY USE_FOLDERS ON)')
	_p('set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "[GENie-Generated-CMake]")')
	_p('add_subdirectory(cmake/%s)', sln.name)
	if sln.startproject then
		_p('set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT %s)', premake.esc(sln.startproject))
	end

	-- Generate gateway CMakeLists.txt that includes all project .cmake files
	local gatewayDir = path.join(sln.location, "cmake", sln.name)
	os.mkdir(gatewayDir)
	local gf, gerr = io.open(path.join(gatewayDir, "CMakeLists.txt"), "wb")
	if gf then
		gf:write('# Auto-generated by GENie\n')
		gf:write('# https://github.com/bkaradzic/GENie\n')
		for i,prj in ipairs(sln.projects) do
			gf:write(string.format('include(%s.cmake)\n', premake.esc(prj.name)))
		end
		gf:close()
	end

	-- Generate CMakePresets.json
	-- Only a single "default" preset with binaryDir — no hardcoded generators.
	-- Users pick their generator via command line or CMakeUserPresets.json.
	local pf, perr = io.open(path.join(sln.location, "CMakePresets.json"), "wb")
	if pf then
		pf:write('{\n')
		pf:write('  "version": 3,\n')
		pf:write('  "configurePresets": [\n')
		pf:write('    {\n')
		pf:write('      "name": "default",\n')
		pf:write('      "binaryDir": "${sourceDir}/build"\n')
		pf:write('    }\n')
		pf:write('  ]\n')
		pf:write('}\n')
		pf:close()
	end
end
