language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

script:
  make

branches:
  only:
    - master

notifications:
  email: false

osx_image:
  xcode61
