--
-- make_swift.lua
-- Generate a Swift project makefile.
--

local make = premake.make

function premake.make_swift(prj)
	-- create a shortcut to the compiler interface
	local swiftc = premake.gettool(prj)
	
	-- build a list of supported target platforms that also includes a generic build
	local platforms = premake.filterplatforms(prj.solution, valac.platforms, "Native")
	
	_p('# %s project makefile autogenerated by GENie', premake.action.current().shortname)
end